version: "3.9"

services:
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql+psycopg2://auth_db:postgres@auth_db:5432/auth_db
      - SECRET_KEY=supersecretkey
    depends_on:
      - auth_db
    volumes:
      - ./auth_service:/app

  auth_db:
    image: postgres:16 # ✅ changed from 17 to 16
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_db
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  analytics_service:
    build:
      context: ./analytics_service
    container_name: analytics_service
    ports:
      - "8001:8000"
    environment:
      - DB_URL=postgresql+asyncpg://analytics_db:postgres@analytics_db:5432/analytics_db
      - SECRET_KEY=shammu1234
    depends_on:
      - analytics_db
    volumes:
      - ./analytics_service:/app

  analytics_db:
    image: postgres:15
    container_name: analytics_db
    restart: always
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: analytics_db
      POSTGRES_PASSWORD: postgres
    volumes:
      - analytics_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  auth_pgdata:
  analytics_pgdata:
