"""create daily_logs table

Revision ID: 6c1a6554fe74
Revises: 
Create Date: 2025-07-23 04:34:56.346901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1a6554fe74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('food', sa.Numeric(), nullable=True),
    sa.Column('travel', sa.Numeric(), nullable=True),
    sa.Column('shopping', sa.Numeric(), nullable=True),
    sa.Column('daily_needs', sa.Numeric(), nullable=True),
    sa.Column('other', sa.Numeric(), nullable=True),
    sa.Column('income', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_logs_id'), 'daily_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_logs_id'), table_name='daily_logs')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###
